language: ruby
rvm:
  - "2.5.5"

## Save bundler deps.
cache: bundler

before_install:
  - gem update --system
  - gem --version

## Disable external link checking to prevent spurious failures because
## of other people's downtime. This can also avoid wasting their
## bandwidth.

## Build all possible jekyll pages for use with link checking.
script:
    - make all

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

# Whitelist all branches
branches:
  only:
  - master
  - /.*/

notifications:
  irc:
    channels:
      - "chat.freenode.net#bitcoin-core-website"
    on_success: change
    on_failure: change
